version: 2.0

flake8-steps: &steps
  - checkout
  - run: sudo pip install flake8
  - run: ./bin/flake8_tests.sh
jobs:
  python-flake8-tests:
    docker:
      - image: circleci/python:3.7.0
    steps: *steps
  legacy-python-flake8-tests:
    docker:
      - image: circleci/python:2.7.15
    steps: *steps
  backend-unit-tests:
    environment:
      COMPOSE_FILE: .circleci/docker-compose.circle.yml
      COMPOSE_PROJECT_NAME: redash
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Images
          command: |
            set -x
            docker run -e CI=true trendava/dero:latest
            docker-compose build --build-arg skip_ds_deps=true
            docker-compose up -d
            sleep 10
      - run:
          name: Create Test Database
          command: docker run -e CI=true trendava/dero:latest
      - run:
          name: Run Tests
          command: docker run -e CI=true trendava/dero:latest
      - run:
          name: Copy Test Results
          command: |
            mkdir -p /tmp/test-results/unit-tests
            docker run -e CI=true trendava/dero:latest
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: coverage.xml
  frontend-unit-tests:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo apt install python-pip
      - run: npm install
      - run: npm run bundle
      - run: npm test
  frontend-e2e-tests:
    environment:
      COMPOSE_FILE: .circleci/docker-compose.cypress.yml
      COMPOSE_PROJECT_NAME: cypress
      PERCY_TOKEN_ENCODED: ZGRiY2ZmZDQ0OTdjMzM5ZWE0ZGQzNTZiOWNkMDRjOTk4Zjg0ZjMxMWRmMDZiM2RjOTYxNDZhOGExMjI4ZDE3MA==
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            docker run -e CI=true trendava/dero:latest
      - run:
          name: Setup Redash server
          command: |
            npm run cypress start
            docker run -e CI=true trendava/dero:latest
      - run:
          name: Execute Cypress tests
          command: docker run -e CI=true trendava/dero:latest
  build-tarball:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo apt install python-pip
      - run: npm install
      - run: .circleci/update_version
      - run: npm run bundle
      - run: npm run build
      - run: .circleci/pack
      - store_artifacts:
          path: /tmp/artifacts/
  build-docker-image:
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - setup_remote_docker
      - checkout
      - run: .circleci/update_version
      - run: .circleci/docker_build
workflows:
  version: 2
  build:
    jobs:
      - python-flake8-tests
      - legacy-python-flake8-tests
      - backend-unit-tests
      - frontend-unit-tests
      - frontend-e2e-tests
      - build-tarball:
          requires:
            - backend-unit-tests
            - frontend-unit-tests
            - frontend-e2e-tests
          filters:
            branches:
              only:
                - master
                - /release\/.*/
      - build-docker-image:
          requires:
            - backend-unit-tests
            - frontend-unit-tests
            - frontend-e2e-tests
          filters:
            branches:
              only:
                - master
                - preview-image
                - /release\/.*/
